### PR TITLE
fixed listen address in SUReplAccessStrict

### PR DESCRIPTION
**Pull request by t0k4rt**
Hello, 
I was deploying our stolon cluster when I spotted an issue with SUReplAccessStrict mode, 
The hba generated get the master listen address instead of the standby address.
This should work as expected with this fix.

### CODE REVIEW

**Comment by sgotti** [comment]
@t0k4rt Thanks for the PR. I'm on vacation so I'll be able to review it at the start of July.

I noticed that in #412 I proposed some tests for `generateHBA` but they weren't pulled in that PR.

Can you please fetch that test (https://github.com/sgotti/stolon/commit/cfc5a03709793f0a76ba5fa5aa95d339a6286330#diff-b0ec7cb5ed37c927cafbf2e430672a47R82` and fix/update it to also catch this case (if not already catching it)? The test without this patch should fails while with this patch is should pass.

**Comment by t0k4rt** [comment]
Thanks for your time :-)
I'll check the test !

**Comment by sgotti** [comment]
@t0k4rt I updated your commit with the tests, see here: https://github.com/sgotti/stolon/commit/3d0d3ca4ec39371632804a074a1586bb23d27064

Can you check/test it and if it's right update this PR with that commit? If you don't have time I'll do it in the next days creating a new PR. Thanks.

**Comment by sgotti** [comment]
@t0k4rt You should just cherry pick only commit https://github.com/sgotti/stolon/commit/3d0d3ca4ec39371632804a074a1586bb23d27064 and remove the other commits.

**Comment by t0k4rt** [comment]
ok I'm working on it

**Comment by t0k4rt** [comment]
Should be okay now

**Comment by sgotti** [comment]
@t0k4rt Can you please use only the commit https://github.com/sgotti/stolon/commit/3d0d3ca4ec39371632804a074a1586bb23d27064 that already has everything (the fix and a good commit message)?

**Comment by sgotti** [comment]
@t0k4rt in that way you have two commits. To only use https://github.com/sgotti/stolon/commit/3d0d3ca4ec39371632804a074a1586bb23d27064 just do 

```
git reset --hard origin/master
git cherry-pick 3d0d3ca
```

**Comment by t0k4rt** [comment]
Ok done

**Comment by sgotti** [comment]
@t0k4rt Thanks! LGTM. Merging

**Comment by t0k4rt** [comment]
Thanks to you :-)

**Pull request merged**
