### PR TITLE
Use service name instead of querying the service to get its IP to connect to the DB

### PR DESCRIPTION
**Pull request by Miyurz**
Querying service for its IP to connect to the database is too tedious and not needed when we can query directly with service name.

### CODE REVIEW

**Comment by mayurgn86** [comment]
@sgotti Updated the commit message

**Comment by mayurgn86** [comment]
@sgotti any update ?

**Comment by sgotti** [comment]
> @sgotti any update ?

Can you please rebase and fix the commit to "k8s example:" (not just "k8s:")? Thanks!

**Comment by mayurgn86** [comment]
> > @sgotti any update ?
> 
> Can you please rebase and fix the commit to "k8s example:" (not just "k8s:")? Thanks!

Done!

**Comment by sgotti** [comment]
@mayurgn86 Thanks! Merging.

**Pull request merged**
