### PR TITLE
Add flags for enabling TLS for store

### PR DESCRIPTION
**Pull request by agalitsyn**
Add capability to use TLS for communication with store, for example with [secure etcd](https://coreos.com/etcd/docs/latest/security.html)

You can check it out by using following steps:
- Rebuild stolon bins from this branch
- Quickly setup secure etcd using [this tool](https://github.com/coreos/etcd/tree/master/hack/tls-setup)
- Run stolon bins using proper values to flags, like:

```
$ cat Procfile 
sentinel: ./bin/stolon-sentinel --cluster-name stolon-cluster --store-backend etcd --store-endpoints localhost:8080 --store-cert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1.pem --store-key $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1-key.pem --store-cacert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/ca.pem
keeper0: ./bin/stolon-keeper --data-dir data/postgres0 --id postgres0 --cluster-name stolon-cluster --pg-repl-username repluser --pg-repl-password replpassword --pg-su-username postgres --pg-su-password qweqwe --pg-bin-path /usr/lib/postgresql/9.4/bin --store-backend etcd --store-endpoints localhost:8080 --store-cert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1.pem --store-key $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1-key.pem --store-cacert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/ca.pem
proxy: ./bin/stolon-proxy --cluster-name stolon-cluster --port 25432 --store-backend etcd --store-endpoints localhost:8080 --store-cert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1.pem --store-key $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/proxy1-key.pem --store-cacert $GOPATH/src/github.com/coreos/etcd/hack/tls-setup/certs/ca.pem
```

### CODE REVIEW

**Comment by agalitsyn** [comment]
Sorry, I didn't recognize integration tests, so I will update them too

**Comment by sgotti** [comment]
@agalitsyn Sorry for the delay and thanks for this PR!

I haven't had time to deeply test it but, since it'll continue working without tls store communication, it LGTM.

Can you please squash it in an unique commit?

**Comment by kayrus** [comment]
@agalitsyn ping

**Comment by kayrus** [comment]
@agalitsyn I'd argue on this PR. I suppose it is better to update libkv to 0.2.1 (it contains https://github.com/docker/libkv/commit/e7f836c5449206f5e3140ce63064a56b0d0443d6)
And pass ClientTLSConfig pointer instead of bunch of strings.

**Comment by agalitsyn** [comment]
@kayrus sure, go ahead, we can close this PR

**Comment by sgotti** [comment]
@agalitsyn @kayrus libkv has been updated to `v0.2.1` in #131. Sorry but I'm missing if someone is going to work on this (to directly pass ClientTLSConfig)?

**Comment by BarnabyShearer** [comment]
v0.2.1 also includes docker/libkv@d635a8e which reverted out the actual implementation for ClientTLSConfig, leaving this pull request as the best working option atm.

**Comment by sgotti** [comment]
Superseded by #208.

**Pull request closed without merging**
