### PR TITLE
*: Make the store prefix configurable

### PR DESCRIPTION
**Pull request by sgotti**
Add a `--store-prefix` option to specify the store prefix.

In the meantime, for consistency, rename StoreBasePath to StorePrefix.

### CODE REVIEW

**Comment by kemko** [comment]
It seems that keeper has ignored --store-prefix key. I changed keeper-entrypoint.sh by add `--store-prefix=/stolon/cluster` but got `no cluster data available` error and in ps stolon-keeper miss this option.

**Comment by sgotti** [comment]
@kemko I tested it and it works. Are you sure you built stolon with this PR included?

**Comment by kemko** [comment]
@sgotti I forgot to add backslash while adding --store-prefix option and bash were interpreted it as another one command. Now it works.

**Comment by sgotti** [comment]
@kemko Thanks! merged.

**Pull request merged**
