### PR TITLE
Release v0.14.0

### PR DESCRIPTION
**Pull request by sgotti**
WIP changelog for release v0.14.0.

### CODE REVIEW

**Comment by maksm90** [comment]
Hi @sgotti!
Unfortunately, the autorestart feature #568 is not safe for parameters (`max_connections`, `max_prepared_transaction`, etc described [here](https://www.postgresql.org/docs/current/hot-standby.html#HOT-STANDBY-ADMIN)) that require the special order of restart of nodes (master -> replicas or back). This feature requires some further development.
I propose to mention explicitly in doc to not use this feature for those problem postgres parameters until it will be done correctly.

**Comment by arunvelsriram** [comment]
@sgotti just wanted to bring it to your notice that #651 was co authorthored.

**Comment by daMupfel** [comment]
Is there any info about when this sweet release might be published :smile:  ?

**Comment by sgotti** [comment]
@maksm90 Thanks. Can you please open a new issue so we can track it? (I was thinking that the next restart after a failed one will work)

@arunvelsriram Thanks. I'll add you.

@daMupfel Probably next week.

**Pull request merged**
