### PR TITLE
Switch uuid package to get around GO-2020-0018

### PR DESCRIPTION
**Pull request by rutgerc-klarrio**
Replace the github.com/satori/go.uuid package with the github.com/google/uuid
package to work around the GO-2020-0018 vulnerability.
The vulnerability is fixed in https://github.com/satori/go.uuid/pull/75,
but a release has never been tagged.

### CODE REVIEW

**Comment by sgotti** [comment]
@rutgerc-klarrio Thanks for the PR, in other packages I preferred to use of https://github.com/gofrs/uuid: https://github.com/agola-io/agola/pull/311

**Comment by rutgerc-klarrio** [comment]
I've changed the uuid lib with the `gofrs` `uuid` package, I have no preference for one over the other.

**Comment by sgotti** [comment]
@rutgerc-klarrio Thanks, can you please squash in a single commit?

**Comment by sgotti** [comment]
Thanks. Merging.

**Pull request merged**
