### PR TITLE
Add configurable store timeout

### PR DESCRIPTION
**Pull request by snailxr**

### CODE REVIEW

**Comment by snailxr** [comment]
@sgotti  Can you review the pull request?

**Comment by sgotti** [comment]
@snailxr integration tests are failing since the new `Store.Config` `Timeout` field introduced in this patch is not set (and will default to 0) when creating the tests stores in https://github.com/sorintlab/stolon/blob/master/tests/integration/utils.go

**Comment by snailxr** [comment]
@sgotti  Is there a easy way to run the integration tests locally?  😃

**Comment by sgotti** [comment]
@snailxr 

* Use a local [agola](www.agola.io) and execute a direct run (also change the `.agola/config.jsonnet` to remove unneeded tasks)

* test a specific store with `INTEGRATION=1 STOLON_TEST_STORE_BACKEND=etcdv3 PARALLEL=20 bash -x ./test`. It requires an etcd v3.x binary in your PATH. It'll use your local installed version of postgres.

**Comment by snailxr** [comment]
@sgotti  The command documents regenerated

**Comment by sgotti** [comment]
@snailxr Thanks! Merging.

**Pull request merged**
