### PR TITLE
Replaced sprintf with net.JoinHostPort to fix bug with ipv6

### PR DESCRIPTION
**Pull request by emdem**

### CODE REVIEW

**Comment by sgotti** [comment]
@emdem Thanks for the PR.

I honestly never tried stolon with ipv6 addresses so if only this change is needed to make it work I'll merge it.

**Comment by emdem** [comment]
@sgotti No problem, thanks for open-sourcing! It may not be the only one, but I'll fix them as I find them. I think this covers the proxy at least.

**Comment by emdem** [comment]
@sgotti I've confirmed that it fixes the issue I was having with the proxy. The following all work:
ipv4 proxy -> ipv6 keeper
ipv6 proxy -> ipv6 keeper
ipv6 proxy -> ipv4 keeper

**Comment by sgotti** [comment]
@emdem Great! We should probably add more tests for ipv6 in future. Merging. Thanks a lot!

**Pull request merged**
