### PR TITLE
Support JSON output in stolonctl status

### PR DESCRIPTION
**Pull request by hmac**
This change allows you to pass a `--format` flag to `stolonctl status` to specify the output format. The available options are `text` (the current output format) and `json`, which produces the same data but in a structured format. The idea is that you can build automation around this information without relying on the semi-structured human-readable format.

### CODE REVIEW

**Comment by sgotti** [comment]
@hmac Thanks for your PR! I'll review it in the next days. 

As a note there was a related issue here: #358

**Comment by hmac** [comment]
Thanks! And apologies, missed that issue!

**Comment by hmac** [comment]
@sgotti thanks for the review and bug spot! I've updated this and it looks like CI has passed now.

**Comment by sgotti** [comment]
@hmac Thanks! Merging.

**Pull request merged**
