### PR TITLE
Add advertise address and port config

### PR DESCRIPTION
**Pull request by daMupfel**
This pull request is here to allow separate configuration for listen address and advertise address.

This is the same pull request as here (but fixed for master branch):
 https://github.com/sorintlab/stolon/pull/455 .

### CODE REVIEW

**Comment by daMupfel** [comment]
Any info of how what i can do to bring this forward?

**Comment by sgotti** [comment]
@daMupfel Are you willing to adopt and develop #455? If you look at its review comments you'll see that one of the main missing things are integration tests. Without them I won't merge it.

**Comment by daMupfel** [comment]
@sgotti I will try. I might need some help/hints though. Will come back to you if that is the case.

**Comment by daMupfel** [comment]
@sgotti  I had a little bit time left today so i finally tried to implement the integration test. I updated my pull request accordingly.

Please tell if this is how you imagined the integration test.

Regards, David

**Comment by daMupfel** [comment]
Any feedback?

**Comment by sgotti** [comment]
@daMupfel That's a good start for an integration test. Thanks. I'm not sure it's covering all the cases but more tests should be added in the future. I'll start merging this as if you don't have more work to do.

**Comment by daMupfel** [comment]
I hope there was not a language barrier here :).

As far as i understood i don't have to do anything for this to get merged, correct?

**Comment by daMupfel** [comment]
Any updates?

**Comment by sgotti** [comment]
@daMupfel sorry for the delay. Merging.

**Comment by daMupfel** [comment]
@sgotti No problems, thank you very much :+1: :smile:

**Pull request merged**
