### PR TITLE
fix : readlink 

### PR DESCRIPTION
**Pull request by romainmeunier**
FreeBSD and OSX have a version of stat derived from NETBsd.
Using perl (native @ MacOs ) one liner

### CODE REVIEW

**Comment by sgotti** [comment]
@romainmeunier Thanks for the PR. @killix opened a similar PR (#158) with a bash only solution. I was waiting for it for being updated using the k8s readlink approach (https://github.com/sorintlab/stolon/pull/158#discussion_r84473543).  If you want you can take over it.

**Comment by sgotti** [comment]
@romainmeunier Thanks for the PR. @killix opened a similar PR (#158) with a bash only solution. I was waiting for it for being updated using the k8s readlink approach (https://github.com/sorintlab/stolon/pull/158#discussion_r84473543).  If you want you can take over it.

**Comment by romainmeunier** [comment]
I'll check the k8s approach.

**Comment by sgotti** [comment]
@romainmeunier @killix would you mind updating this PR or #158 with the k8s bash function? If you don't have time I'll create a new PR in the next days. Thanks!

**Comment by sgotti** [comment]
Closing this in favor of #158. Thanks!

**Pull request closed without merging**
